"""
NRIE · Contracts · Interfaces
=============================
Repository and read-API interfaces (Protocols). Implementations live in
infrastructure/api; the Orchestrator and tests depend on THESE abstractions, not
concretions. No business logic in interfaces.
"""
from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable

from .dto import BusinessContextDTO, EnterpriseNodeDTO, KnowledgeDTO, ResourceDTO


@runtime_checkable
class EnterpriseRepository(Protocol):
    def save(self, node: "object") -> None: ...
    def get(self, entity_id: str) -> Optional["object"]: ...
    def children(self, parent_id: Optional[str]) -> List["object"]: ...
    def all(self) -> List["object"]: ...


@runtime_checkable
class ResourceRepository(Protocol):
    def save(self, resource: "object") -> None: ...
    def get(self, resource_id: str) -> Optional["object"]: ...
    def by_hierarchy(self, hierarchy_ref: str) -> List["object"]: ...
    def all(self) -> List["object"]: ...


@runtime_checkable
class BusinessContextRepository(Protocol):
    def save(self, ctx: "object") -> None: ...
    def for_target(self, attached_to: str) -> Optional["object"]: ...


@runtime_checkable
class KnowledgeRepository(Protocol):
    def save(self, record: "object") -> None: ...
    def by_kind(self, kind: Optional[str]) -> List["object"]: ...


@runtime_checkable
class NRIEReadAPI(Protocol):
    def enterprise_hierarchy(self, root_id: Optional[str] = None) -> List[EnterpriseNodeDTO]: ...
    def resource_hierarchy(self, hierarchy_ref: Optional[str] = None,
                           resource_type: Optional[str] = None) -> List[ResourceDTO]: ...
    def business_context(self, attached_to: str) -> Optional[BusinessContextDTO]: ...
    def knowledge(self, kind: Optional[str] = None) -> List[KnowledgeDTO]: ...
