"""
core/hypothesis_generator.py
============================
Generate novel hypotheses for unknown network issues using Claude.

When internal diagnosis fails, Claude generates creative hypotheses
based on few-shot examples from past incidents.
"""

import logging
import re
from dataclasses import dataclass
from typing import List, Dict, Optional, Any

logger = logging.getLogger(__name__)


@dataclass
class GeneratedHypothesis:
    """A hypothesis generated by Claude for investigation."""
    hypothesis: str  # The main hypothesis
    reasoning: str  # Why this might be the cause
    test_steps: List[str]  # How to verify this hypothesis
    suggested_fix: Optional[str] = None  # If confirmed, what to do
    confidence: float = 0.5  # Estimated confidence


class AIHypothesisGenerator:
    """Generate novel hypotheses for unknown network issues."""

    def __init__(self, ai_call: callable, pattern_db: Optional[Any] = None):
        """
        Parameters
        ----------
        ai_call : callable
            LLM function to generate hypotheses (e.g., ask_ai)
        pattern_db : PatternDatabase, optional
            Database of past incidents for few-shot examples
        """
        self.ai = ai_call
        self.pattern_db = pattern_db
        logger.info("AIHypothesisGenerator initialized")

    def generate_hypotheses(self,
                           problem: Any,
                           max_hypotheses: int = 3) -> List[GeneratedHypothesis]:
        """
        Generate novel hypotheses for an unknown issue.

        Uses few-shot learning with past similar incidents.

        Parameters
        ----------
        problem : ProblemStatement
            The problem to generate hypotheses for
        max_hypotheses : int
            Maximum hypotheses to generate (default 3)

        Returns
        -------
        List[GeneratedHypothesis]
            Generated hypotheses ready for user investigation
        """
        logger.info(
            f"Generating {max_hypotheses} hypotheses for: {problem.raw_text[:60]}..."
        )

        # STEP 1: Get few-shot examples from past incidents
        examples = self._get_few_shot_examples(problem)

        # STEP 2: Build prompt
        prompt = self._build_generation_prompt(problem, examples, max_hypotheses)

        # STEP 3: Call Claude
        try:
            response = self.ai(prompt)
        except Exception as e:
            logger.error(f"AI hypothesis generation failed: {e}")
            return []

        # STEP 4: Parse response
        hypotheses = self._parse_hypotheses_from_response(response, max_hypotheses)

        logger.info(f"Generated {len(hypotheses)} hypothesis/hypotheses")
        return hypotheses

    def _get_few_shot_examples(self, problem: Any) -> List[Dict[str, Any]]:
        """Get similar past incidents as few-shot examples."""
        if not self.pattern_db:
            return []

        try:
            # Get 3-5 similar incidents
            examples = self.pattern_db.find_similar(
                problem.raw_text,
                top_k=5,
                min_confidence=0.3  # Include lower confidence ones for learning
            )

            logger.info(f"Found {len(examples)} similar past incidents")
            return examples[:5]

        except Exception as e:
            logger.warning(f"Could not retrieve few-shot examples: {e}")
            return []

    def _build_generation_prompt(self,
                                problem: Any,
                                examples: List[Dict],
                                max_hypotheses: int) -> str:
        """Build Claude prompt to generate hypotheses."""
        prompt = f"""You are an expert network engineer. Generate {max_hypotheses} NOVEL hypotheses for this network issue.

PROBLEM DESCRIPTION:
  Type: {problem.raw_text}
  Scope: {problem.scope} (where in the network)
  Symptom: {problem.symptom} (what's wrong)
  Severity: {problem.severity} (how bad)
  Affected Devices: {', '.join(problem.affected_devices) if problem.affected_devices else 'Unknown'}

SIMILAR PAST INCIDENTS (for context, do NOT repeat these):
"""

        if examples:
            for i, ex in enumerate(examples[:5], 1):
                prompt += f"""
{i}. Problem: {ex.get('problem_description', 'Unknown')[:100]}
   Root Cause: {ex.get('root_cause', 'Unknown')}
   Fix: {ex.get('fix_applied', 'Unknown')[:50]}
   Success Rate: {ex.get('confidence', 0):.0%}
"""
        else:
            prompt += "\nNo similar incidents found in database.\n"

        prompt += f"""

GENERATE {max_hypotheses} NOVEL HYPOTHESES:

For each hypothesis, provide:
1. HYPOTHESIS: [one sentence describing the potential root cause]
2. REASONING: [why this could cause the observed symptoms]
3. TEST: [specific diagnostic commands or checks to verify]
4. FIX: [if confirmed, what would be the fix]
5. CONFIDENCE: [0-100, estimated likelihood]

Format your response EXACTLY as:

HYPOTHESIS 1:
Hypothesis: [text]
Reasoning: [text]
Test: [text]
Fix: [text]
Confidence: [0-100]

HYPOTHESIS 2:
[same format]

Remember:
- These should be NOVEL (not in the past incidents list)
- Be specific and technical
- Include realistic debugging steps
- Consider infrastructure constraints (no physical access needed)
- Include network config issues, BGP problems, MTU mismatches, routing issues, interface faults, QoS problems, etc.
"""

        return prompt

    def _parse_hypotheses_from_response(self,
                                       response: str,
                                       max_hypotheses: int) -> List[GeneratedHypothesis]:
        """Parse Claude's response into structured hypotheses."""
        hypotheses = []

        # Split by "HYPOTHESIS N:"
        pattern = r'HYPOTHESIS\s+\d+:(.*?)(?=HYPOTHESIS\s+\d+:|$)'
        matches = re.findall(pattern, response, re.DOTALL | re.IGNORECASE)

        for match_text in matches[:max_hypotheses]:
            try:
                hyp = self._parse_single_hypothesis(match_text)
                if hyp:
                    hypotheses.append(hyp)
            except Exception as e:
                logger.warning(f"Failed to parse hypothesis: {e}")

        return hypotheses

    def _parse_single_hypothesis(self, text: str) -> Optional[GeneratedHypothesis]:
        """Parse a single hypothesis from text."""
        try:
            # Extract fields
            hypothesis = self._extract_field(text, "Hypothesis", "hypothesis")
            reasoning = self._extract_field(text, "Reasoning", "reasoning")
            test = self._extract_field(text, "Test", "test")
            fix = self._extract_field(text, "Fix", "fix")
            confidence_str = self._extract_field(text, "Confidence", "confidence")

            if not hypothesis:
                return None

            # Parse confidence
            try:
                confidence = int(re.search(r'\d+', confidence_str or "50").group(0)) / 100
            except:
                confidence = 0.5

            # Parse test steps
            test_steps = [s.strip() for s in test.split("\n") if s.strip()]

            return GeneratedHypothesis(
                hypothesis=hypothesis,
                reasoning=reasoning,
                test_steps=test_steps,
                suggested_fix=fix,
                confidence=confidence
            )

        except Exception as e:
            logger.error(f"Hypothesis parsing error: {e}")
            return None

    def _extract_field(self, text: str, field_name: str, fallback: str = "") -> str:
        """Extract a field from hypothesis text."""
        pattern = rf'{field_name}:\s*(.+?)(?=\n[A-Z][a-z]+:|$)'
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)

        if match:
            content = match.group(1).strip()
            # Clean up markdown code blocks
            content = re.sub(r'```.*?```', '', content, flags=re.DOTALL)
            return content.strip()

        return fallback

    def print_hypotheses(self, hypotheses: List[GeneratedHypothesis]) -> str:
        """Generate human-readable hypothesis report."""
        if not hypotheses:
            return "❌ Could not generate hypotheses\n"

        report = "🤔 GENERATED HYPOTHESES\n"
        report += "=" * 60 + "\n\n"

        # Sort by confidence (highest first)
        sorted_hyps = sorted(hypotheses, key=lambda h: h.confidence, reverse=True)

        for i, hyp in enumerate(sorted_hyps, 1):
            report += f"HYPOTHESIS {i} (Confidence: {hyp.confidence:.0%})\n"
            report += f"─────────────────────────────────\n"
            report += f"Hypothesis: {hyp.hypothesis}\n\n"

            report += f"Why this could be the cause:\n"
            report += f"{hyp.reasoning}\n\n"

            if hyp.test_steps:
                report += f"How to verify:\n"
                for step in hyp.test_steps:
                    report += f"  • {step}\n"
                report += "\n"

            if hyp.suggested_fix:
                report += f"If confirmed, fix:\n"
                report += f"{hyp.suggested_fix}\n\n"

            report += "\n"

        report += "=" * 60 + "\n"
        report += f"Total: {len(hypotheses)} hypotheses generated\n"
        report += "\nNext: Pick the most likely hypothesis and test it!\n"

        return report
